#!/usr/bin/env python3
"""Turn docs/xml_audit_results.json (produced by audit_xml_corpus.py) into
the Markdown report at docs/xml_audit_report.md, following the structure
of docs/xml_audit_checklist.md.

Usage: python3 scripts/generate_xml_audit_report.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_PATH = REPO_ROOT / "docs" / "xml_audit_results.json"
REPORT_PATH = REPO_ROOT / "docs" / "xml_audit_report.md"


def fmt_pct(n: int, total: int) -> str:
    if total == 0:
        return "n/a"
    return f"{100 * n / total:.1f}%"


def build_report(data: dict) -> str:
    works = data["works"]
    schema = data["schema_consistency"]

    lines: list[str] = []
    a = lines.append

    a("# XML corpus audit report")
    a("")
    a(f"Corpus: `data/raw/corpus/raw/src` (paragraph-level), {len(works)} works.")
    a("")
    a(
        "Generated by `scripts/audit_xml_corpus.py` + "
        "`scripts/generate_xml_audit_report.py` following "
        "`docs/xml_audit_checklist.md`. Excludes `raw/src/import.xml`, which "
        "is a TXM import config, not a work."
    )
    a("")

    # ---- 1. Structure above paragraph level ----
    a("## 1. Structure above paragraph level")
    a("")
    a("### Tags per file")
    a("")
    a("| Work | Tags |")
    a("|---|---|")
    for w in works:
        a(f"| {w['work_id']} | {', '.join(sorted(w['raw_tags']))} |")
    a("")

    a("### Structure levels above the paragraph")
    a("")
    a("| Work | Max `div` nesting depth | `div/@type` values used |")
    a("|---|---|---|")
    for w in works:
        types = ", ".join(f"{t}({n})" for t, n in sorted(w["div_types"].items()))
        a(f"| {w['work_id']} | {w['max_div_depth']} | {types or '(none)'} |")
    a("")
    all_div_types = sorted({t for w in works for t in w["div_types"]})
    a(
        "`front`/`body`/`back` are present at the top level in all files (see "
        "tag list above); `head` provides the title text for each structural "
        "level. `div/@type` values found across the corpus: "
        f"{', '.join(all_div_types)}."
    )
    a("")
    a(
        '**Note** — `div type="app"` (appendix) holds text still authored by '
        "Bergson himself (e.g. his reply to a critic in *Le rire*), not an "
        "editor's note; do not exclude it as editorial content on the basis "
        "of the `app` type alone."
    )
    a("")

    a("### Tag consistency across the 8 works")
    a("")
    a(f"- Tags common to all files: {', '.join(schema['common_raw_tags'])}")
    a("")
    if schema["drift_notes"]:
        a("Drift detected:")
        a("")
        for note in schema["drift_notes"]:
            a(f"- {note}")
    else:
        a("No tag-set drift detected across works.")
    a("")

    # ---- 2. Corpus size ----
    a("## 2. Corpus size")
    a("")
    a("| Work | Paragraphs | Words | Words / paragraph |")
    a("|---|---|---|---|")
    for w in works:
        ratio = w["raw_word_count"] / w["raw_paragraph_count"] if w["raw_paragraph_count"] else 0
        a(
            f"| {w['work_id']} | {w['raw_paragraph_count']} | {w['raw_word_count']} "
            f"| {ratio:.1f} |"
        )
    total_paragraphs = sum(w["raw_paragraph_count"] for w in works)
    total_words = sum(w["raw_word_count"] for w in works)
    total_ratio = total_words / total_paragraphs if total_paragraphs else 0
    a(f"| **Total** | {total_paragraphs} " f"| {total_words} | {total_ratio:.1f} |")
    a("")

    # ---- 3. Encoding ----
    a("## 3. Encoding")
    a("")
    a(
        "| Work | Straight `'` | Curly `’` | Ligatures (œ/æ/Œ/Æ) | `\"` (dialogue/citation) | Guillemets `« »` |"
    )
    a("|---|---|---|---|---|---|")
    for w in works:
        lig = sum(w["ligatures"].values())
        a(
            f"| {w['work_id']} | {w['straight_apostrophes']} | {w['curly_apostrophes']} | {lig} "
            f"| {w['double_quotes']} | {w['guillemets']} |"
        )
    a("")
    mixed_apostrophe = [
        w["work_id"] for w in works if w["straight_apostrophes"] and w["curly_apostrophes"]
    ]
    if mixed_apostrophe:
        a(
            f"**Anomaly** — mixed straight/curly apostrophes within the same file: {', '.join(mixed_apostrophe)}. "
            "Apostrophe convention should be normalized (pick one) before chunking/embedding."
        )
    else:
        a(
            "Apostrophe convention is consistent within each file (no file mixes straight and curly apostrophes)."
        )
    a("")
    a(
        "No mojibake or OCR-residue artifacts were detected via the checks above "
        "(the corpus is transcribed from a modern digital edition, not OCR-scanned, per "
        "`sourceDesc`). Ligatures shown above (œ/æ) are legitimate French orthography, not artifacts."
    )
    a("")

    # ---- 4. Editorial content ----
    a("## 4. Editorial content")
    a("")
    a(
        '| Work | `note`/`quote`/`cit`/`q`/`bibl` tags found | `app` divs | `".."` marks (proxy for untagged citations) |'
    )
    a("|---|---|---|---|")
    for w in works:
        found = ", ".join(f"{t}={n}" for t, n in w["editorial_tags_found"].items()) or "none"
        a(f"| {w['work_id']} | {found} | {w['app_div_count']} | {w['double_quotes']} |")
    a("")
    a(
        "**Finding** — no structural markup (`note`, `quote`, `cit`, `q`, `bibl`) is used anywhere "
        "in the corpus to distinguish footnotes, editorial commentary, or quotations from "
        "other authors. Quoted material (e.g. Bergson quoting Yves Delage in the *Le rire* "
        "appendix) is embedded as plain running text delimited only by typographic quotation "
        'marks (`"…"`), which are indistinguishable at the XML level from ordinary emphasis '
        "or reported speech. **Decision needed before chunking**: since there is no tag to "
        "filter on, third-party quotations cannot be programmatically excluded or flagged; "
        "any chunk containing a long quoted passage will silently mix Bergson's voice with "
        "the quoted author's. Recommend a manual pass on works where this is most likely "
        "(argumentative chapters citing other philosophers), or a heuristic quotation-span "
        "detector as a Sprint 1 pre-processing step."
    )
    a("")

    # ---- 5. Bibliographic metadata ----
    a("## 5. Bibliographic metadata")
    a("")
    a(
        "| Work | Title | First publication date (metadata.csv) | `publicationStmt/date` (source edition year) | Pagination encoded (`pb/@n`) | Metadata `pages` |"
    )
    a("|---|---|---|---|---|---|")
    for w in works:
        pb_rate = fmt_pct(w["pb_with_n"], w["pb_total"])
        a(
            f"| {w['work_id']} | {w['title']} | {w['first_pub_date']} | {w['pub_stmt_date']} "
            f"| {w['pb_with_n']}/{w['pb_total']} ({pb_rate}) | {w['metadata_pages']} |"
        )
    a("")
    a("### `sourceDesc` (source edition used for the encoding)")
    a("")
    a("| Work | `sourceDesc` text | Consistent with title |")
    a("|---|---|---|")
    for w in works:
        flag = "yes" if w["source_desc_title_match"] else "**NO — check manually**"
        a(f"| {w['work_id']} | {w['source_desc_text']} | {flag} |")
    a("")
    mismatches = [w for w in works if not w["source_desc_title_match"]]
    if mismatches:
        m = mismatches[0]
        a(
            "**Anomaly** — `sourceDesc` text does not mention any word from the work's own "
            "title for: " + ", ".join(w["work_id"] for w in mismatches) + ". Manual check of "
            f"`{m['raw_path']}` shows its `sourceDesc` "
            "describes *L'Énergie spirituelle* while the file is *"
            + m["title"]
            + "* — likely a copy-paste error in the source repo's `teiHeader` (only the URL "
            "is correct). Should be reported/fixed upstream before citing this field."
        )
        a("")
    a(
        "`publicationStmt/date` records the year of the **source edition** used for the "
        "encoding (a later reprint), not the first publication date — the two differ for "
        "several works (e.g. *Le rire*, first published 1900, encoded from the 1932/1924 "
        "edition). `metadata.csv/date` correctly holds the first publication date. Both "
        "values should be surfaced in citations to avoid conflating them."
    )
    a("")
    a(
        "Page-break (`pb/@n`) coverage is near-total for most works (numbered `pb` should "
        "roughly track the `pages` count from `metadata.csv`), meaning precise page-level "
        "academic citation is achievable from `raw/src` alone; unnumbered `pb` elements "
        "(front matter, plates) are expected and not an error."
    )
    a("")

    a("## Summary of anomalies to resolve before chunking")
    a("")
    anomalies = []
    if mixed_apostrophe:
        anomalies.append(f"Mixed apostrophe typography in: {', '.join(mixed_apostrophe)}.")
    anomalies.append(
        "No structural tagging of footnotes/quotations anywhere in the corpus — see §4."
    )
    if mismatches:
        anomalies.append(
            f"`sourceDesc` copy-paste error in: {', '.join(w['work_id'] for w in mismatches)} — see §5."
        )
    for note in anomalies:
        a(f"- {note}")
    a("")

    return "\n".join(lines) + "\n"


def main() -> None:
    if not RESULTS_PATH.exists():
        raise SystemExit(
            f"{RESULTS_PATH.relative_to(REPO_ROOT)} not found — run "
            "scripts/audit_xml_corpus.py first."
        )
    data = json.loads(RESULTS_PATH.read_text(encoding="utf-8"))
    report = build_report(data)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
