#!/usr/bin/env python3
"""Turn docs/xml_audit_results.json (produced by audit_xml_corpus.py) into
the Markdown report at docs/xml_audit_report.md, following the structure
of docs/xml_audit_checklist.md.

Usage: python3 scripts/generate_xml_audit_report.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESULTS_PATH = REPO_ROOT / "docs" / "xml_audit_results.json"
REPORT_PATH = REPO_ROOT / "docs" / "xml_audit_report.md"


def fmt_pct(n: int, total: int) -> str:
    if total == 0:
        return "n/a"
    return f"{100 * n / total:.1f}%"


def build_report(data: dict) -> str:
    works = data["works"]
    schema = data["schema_consistency"]

    lines: list[str] = []
    a = lines.append

    a("# XML corpus audit report")
    a("")
    a(f"Corpus: `data/raw/corpus/raw/src` (paragraph-level) and "
      f"`data/raw/corpus/tag/src` (word-level), {len(works)} works.")
    a("")
    a("Generated by `scripts/audit_xml_corpus.py` + "
      "`scripts/generate_xml_audit_report.py` following "
      "`docs/xml_audit_checklist.md`. Excludes `raw/src/import.xml`, which "
      "is a TXM import config, not a work.")
    a("")

    # ---- 1. Tags and schema ----
    a("## 1. Tags and schema")
    a("")
    a("### Tags per file")
    a("")
    a("| Work | raw/src tags | tag/src tags |")
    a("|---|---|---|")
    for w in works:
        a(f"| {w['work_id']} | {', '.join(sorted(w['raw_tags']))} | {', '.join(sorted(w['tag_tags']))} |")
    a("")

    a("### POS values per file (tag/src, `w/@pos`)")
    a("")
    a("| Work | POS values (count) |")
    a("|---|---|")
    for w in works:
        vals = ", ".join(f"{pos}={n}" for pos, n in sorted(w["pos_values"].items()))
        a(f"| {w['work_id']} | {vals} |")
    a("")
    suspicious = {w["work_id"]: w["pos_suspicious"] for w in works if w["pos_suspicious"]}
    if suspicious:
        a("**Anomaly** — suspicious `pos` values found (empty string or literal "
          "`\"nan\"`, likely a pandas/export artifact rather than a real UD tag):")
        a("")
        for wid, ctr in suspicious.items():
            a(f"- {wid}: {ctr}")
        a("")
    else:
        a("No suspicious POS values (empty or `nan`) found.")
        a("")

    a("### Schema consistency across the 8 works")
    a("")
    a(f"- Tags common to all `raw/src` files: {', '.join(schema['common_raw_tags'])}")
    a(f"- Tags common to all `tag/src` files: {', '.join(schema['common_tag_tags'])}")
    a("")
    if schema["drift_notes"]:
        a("Drift detected:")
        a("")
        for note in schema["drift_notes"]:
            a(f"- {note}")
    else:
        a("No tag- or attribute-set drift detected across works.")
    a("")

    # ---- 2. Corpus size ----
    a("## 2. Corpus size")
    a("")
    a("| Work | Paragraphs (raw) | Paragraphs (tag) | Match | Words (tag, `<w>` count) | Words (raw, whitespace-split) |")
    a("|---|---|---|---|---|---|")
    for w in works:
        match = "yes" if w["raw_paragraph_count"] == w["tag_paragraph_count"] else "**NO**"
        a(f"| {w['work_id']} | {w['raw_paragraph_count']} | {w['tag_paragraph_count']} | {match} "
          f"| {w['tag_word_count']} | {w['raw_word_count']} |")
    a(f"| **Total** | {sum(w['raw_paragraph_count'] for w in works)} "
      f"| {sum(w['tag_paragraph_count'] for w in works)} | "
      f"| {sum(w['tag_word_count'] for w in works)} | {sum(w['raw_word_count'] for w in works)} |")
    a("")

    # ---- 3. Structure above paragraph level ----
    a("## 3. Structure above paragraph level")
    a("")
    a("| Work | Max `div` nesting depth | `div/@type` values used |")
    a("|---|---|---|")
    for w in works:
        types = ", ".join(f"{t}({n})" for t, n in sorted(w["div_types"].items()))
        a(f"| {w['work_id']} | {w['max_div_depth']} | {types or '(none)'} |")
    a("")
    all_div_types = sorted({t for w in works for t in w["div_types"]})
    a("`front`/`body`/`back` are present at the top level in all files (see "
      "tag list above); `head` provides the title text for each structural "
      "level. `div/@type` values found across the corpus: "
      f"{', '.join(all_div_types)}.")
    a("")
    a("**Note** — `div type=\"app\"` (appendix) holds text still authored by "
      "Bergson himself (e.g. his reply to a critic in *Le rire*), not an "
      "editor's note; do not exclude it as editorial content on the basis "
      "of the `app` type alone.")
    a("")

    # ---- 4. Lemmatization quality ----
    a("## 4. Lemmatization quality")
    a("")
    a("| Work | Tokens | Non-empty lemma | Lemmatization rate |")
    a("|---|---|---|---|")
    for w in works:
        a(f"| {w['work_id']} | {w['lemma_total']} | {w['lemma_nonempty']} "
          f"| {fmt_pct(w['lemma_nonempty'], w['lemma_total'])} |")
    total_lemma_total = sum(w["lemma_total"] for w in works)
    total_lemma_nonempty = sum(w["lemma_nonempty"] for w in works)
    a(f"| **Total** | {total_lemma_total} | {total_lemma_nonempty} | {fmt_pct(total_lemma_nonempty, total_lemma_total)} |")
    a("")

    # ---- 5. Encoding ----
    a("## 5. Encoding")
    a("")
    a("| Work | Straight `'` | Curly `’` | Ligatures (œ/æ/Œ/Æ) | `\"` (dialogue/citation) | Guillemets `« »` |")
    a("|---|---|---|---|---|---|")
    for w in works:
        lig = sum(w["ligatures"].values())
        a(f"| {w['work_id']} | {w['straight_apostrophes']} | {w['curly_apostrophes']} | {lig} "
          f"| {w['double_quotes']} | {w['guillemets']} |")
    a("")
    mixed_apostrophe = [w["work_id"] for w in works if w["straight_apostrophes"] and w["curly_apostrophes"]]
    if mixed_apostrophe:
        a(f"**Anomaly** — mixed straight/curly apostrophes within the same file: {', '.join(mixed_apostrophe)}. "
          "Apostrophe convention should be normalized (pick one) before chunking/embedding.")
    else:
        a("Apostrophe convention is consistent within each file (no file mixes straight and curly apostrophes).")
    a("")
    a("No mojibake or OCR-residue artifacts were detected via the checks above "
      "(the corpus is transcribed from a modern digital edition, not OCR-scanned, per "
      "`sourceDesc`). Ligatures shown above (œ/æ) are legitimate French orthography, not artifacts.")
    a("")

    # ---- 6. Editorial content ----
    a("## 6. Editorial content")
    a("")
    a("| Work | `note`/`quote`/`cit`/`q`/`bibl` tags found | `app` divs | `\"..\"` marks (proxy for untagged citations) |")
    a("|---|---|---|---|")
    for w in works:
        found = ", ".join(f"{t}={n}" for t, n in w["editorial_tags_found"].items()) or "none"
        a(f"| {w['work_id']} | {found} | {w['app_div_count']} | {w['double_quotes']} |")
    a("")
    a("**Finding** — no structural markup (`note`, `quote`, `cit`, `q`, `bibl`) is used anywhere "
      "in the corpus to distinguish footnotes, editorial commentary, or quotations from "
      "other authors. Quoted material (e.g. Bergson quoting Yves Delage in the *Le rire* "
      "appendix) is embedded as plain running text delimited only by typographic quotation "
      "marks (`\"…\"`), which are indistinguishable at the XML level from ordinary emphasis "
      "or reported speech. **Decision needed before chunking**: since there is no tag to "
      "filter on, third-party quotations cannot be programmatically excluded or flagged; "
      "any chunk containing a long quoted passage will silently mix Bergson's voice with "
      "the quoted author's. Recommend a manual pass on works where this is most likely "
      "(argumentative chapters citing other philosophers), or a heuristic quotation-span "
      "detector as a Sprint 1 pre-processing step.")
    a("")

    # ---- 7. Cross-source alignment ----
    a("## 7. Cross-source alignment")
    a("")
    a("| Work | raw `<p>` has an id/n attribute | tag `<p n=…>` present | tag `n` values unique | raw vs tag paragraph count match |")
    a("|---|---|---|---|---|")
    for w in works:
        match = "yes" if w["raw_paragraph_count"] == w["tag_paragraph_count"] else "**NO**"
        a(f"| {w['work_id']} | {'yes' if w['raw_p_has_id'] else '**no**'} | "
          f"{'yes' if w['tag_p_count'] else 'no'} | {'yes' if w['tag_p_ids_unique'] else '**no**'} | {match} |")
    a("")
    a("**Finding** — `raw/src` paragraphs carry **no identifier at all** (`<p>` has no "
      "`@n`/`@xml:id`); `tag/src` paragraphs carry a sequential `@n` (1..N, unique per "
      "file, not reset per `div`). There is therefore no explicit shared key between the "
      "two sources today. Where the per-work paragraph counts match (see table above), "
      "**positional alignment** (n-th `<p>` in raw/src ↔ `<p n=\"n\">` in tag/src) is a "
      "safe join key; any row where the counts differ must be re-segmented or manually "
      "checked before relying on positional alignment. The ROADMAP's planned join on "
      "\"paragraph id\" (Sprint 1) will need to either add explicit ids to raw/src or "
      "formalize this positional join.")
    a("")

    # ---- 8. Bibliographic metadata ----
    a("## 8. Bibliographic metadata")
    a("")
    a("| Work | Title | First publication date (metadata.csv) | `publicationStmt/date` (source edition year) | Pagination encoded (`pb/@n`) | Metadata `pages` |")
    a("|---|---|---|---|---|---|")
    for w in works:
        pb_rate = fmt_pct(w["pb_with_n"], w["pb_total"])
        a(f"| {w['work_id']} | {w['title']} | {w['first_pub_date']} | {w['pub_stmt_date']} "
          f"| {w['pb_with_n']}/{w['pb_total']} ({pb_rate}) | {w['metadata_pages']} |")
    a("")
    a("### `sourceDesc` (source edition used for the encoding)")
    a("")
    a("| Work | `sourceDesc` text | Consistent with title |")
    a("|---|---|---|")
    for w in works:
        flag = "yes" if w["source_desc_title_match"] else "**NO — check manually**"
        a(f"| {w['work_id']} | {w['source_desc_text']} | {flag} |")
    a("")
    mismatches = [w for w in works if not w["source_desc_title_match"]]
    if mismatches:
        m = mismatches[0]
        a("**Anomaly** — `sourceDesc` text does not mention any word from the work's own "
          "title for: " + ", ".join(w["work_id"] for w in mismatches) + ". Manual check of "
          f"`{m['raw_path']}` shows its `sourceDesc` "
          "describes *L'Énergie spirituelle* while the file is *" + m["title"] +
          "* — likely a copy-paste error in the source repo's `teiHeader` (only the URL "
          "is correct). Should be reported/fixed upstream before citing this field.")
        a("")
    a("`publicationStmt/date` records the year of the **source edition** used for the "
      "encoding (a later reprint), not the first publication date — the two differ for "
      "several works (e.g. *Le rire*, first published 1900, encoded from the 1932/1924 "
      "edition). `metadata.csv/date` correctly holds the first publication date. Both "
      "values should be surfaced in citations to avoid conflating them.")
    a("")
    a("Page-break (`pb/@n`) coverage is near-total for most works (numbered `pb` should "
      "roughly track the `pages` count from `metadata.csv`), meaning precise page-level "
      "academic citation is achievable from `raw/src` alone; unnumbered `pb` elements "
      "(front matter, plates) are expected and not an error.")
    a("")

    a("## Summary of anomalies to resolve before chunking")
    a("")
    anomalies = []
    if suspicious:
        anomalies.append(f"Suspicious `pos` values (`nan`/empty) in: {', '.join(suspicious)}.")
    if mixed_apostrophe:
        anomalies.append(f"Mixed apostrophe typography in: {', '.join(mixed_apostrophe)}.")
    anomalies.append("No structural tagging of footnotes/quotations anywhere in the corpus — see §6.")
    anomalies.append("No shared paragraph identifier between raw/src and tag/src — see §7.")
    if mismatches:
        anomalies.append(f"`sourceDesc` copy-paste error in: {', '.join(w['work_id'] for w in mismatches)} — see §8.")
    mismatched_counts = [w["work_id"] for w in works if w["raw_paragraph_count"] != w["tag_paragraph_count"]]
    if mismatched_counts:
        anomalies.append(f"Paragraph count mismatch between raw/src and tag/src in: {', '.join(mismatched_counts)} — see §2/§7.")
    for note in anomalies:
        a(f"- {note}")
    a("")

    return "\n".join(lines) + "\n"


def main() -> None:
    if not RESULTS_PATH.exists():
        raise SystemExit(
            f"{RESULTS_PATH.relative_to(REPO_ROOT)} not found — run "
            "scripts/audit_xml_corpus.py first."
        )
    data = json.loads(RESULTS_PATH.read_text(encoding="utf-8"))
    report = build_report(data)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
